{"hierarchy":{"paths":[[]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easycode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easycode"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"title":"EasyCode","externalID":"EasyCode","roleHeading":"Framework","modules":[{"name":"EasyCode"}],"role":"collection","symbolKind":"module"},"topicSections":[{"identifiers":["doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/BiometricIDAuth","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ConsoleLogger","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ContactsWorker","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/CoreDataManager","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DebounceProvider","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DependencyFactory","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DispatchWorker","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DynamicHeightCollectionView","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/HostingView","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/JSONWorker","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/JailbreakDetection","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/KeychainService","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/LocalFileManager","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Logger","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/MeasureTest","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkManager","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkMonitor","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NotificationAction","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NotificationManager","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Observable","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PaddedLabel","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PasswordValidationFactory","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PasswordValidator","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PerformManager","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/SelfSizedTableView","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/TemporaryImageCache","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ThreadSafe","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/TipViewController","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/UnmanagedWrapper","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/UserDefaultsStore"],"title":"Classes"},{"identifiers":["doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DataBaseNameProtocol","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DeviceInformation","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EncryptionCryptoProtocol","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EndPointProtocol","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/FolderTypeProtocol","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ImageCache","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/JailbreakDetectionService","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/KeyboardNotificationProtocol","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/KeychainKeyProtocol","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkMonitorDelegate","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkResponseProtocol","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NotificationManagerDelegate","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PasswordValidationStrategy","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/UserDefaultsStoreKey"],"title":"Protocols"},{"identifiers":["doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/MailConfiguration","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/RegularExpression"],"title":"Structures"},{"identifiers":["doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/HTTPHeaders","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/MultipartFormDataParameter","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Parameters"],"title":"Type Aliases"},{"identifiers":["doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EncodingType","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EncryptionError","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/HTTPMethod","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ImageFilter","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkError","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ValidationRule"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/AVFoundation","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Foundation","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NaturalLanguage","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Swift","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/UIKit"]}],"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"Overview"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode"},"sections":[],"references":{"doc://salmik.EasyCode/documentation/EasyCode/JailbreakDetectionService":{"abstract":[],"navigatorTitle":[{"text":"JailbreakDetectionService","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/JailbreakDetectionService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JailbreakDetectionService"}],"title":"JailbreakDetectionService","url":"\/documentation\/easycode\/jailbreakdetectionservice"},"doc://salmik.EasyCode/documentation/EasyCode/EncryptionError":{"title":"EncryptionError","type":"topic","abstract":[{"type":"text","text":"Enum defining various encryption-related errors."}],"url":"\/documentation\/easycode\/encryptionerror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncryptionError"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EncryptionError","navigatorTitle":[{"text":"EncryptionError","kind":"identifier"}]},"doc://salmik.EasyCode/documentation/EasyCode/NotificationAction":{"url":"\/documentation\/easycode\/notificationaction","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NotificationAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NotificationAction","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NotificationAction","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"NotificationAction"}]},"doc://salmik.EasyCode/documentation/EasyCode/NotificationManager":{"title":"NotificationManager","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NotificationManager","abstract":[{"type":"text","text":"A class that manages subscriptions to notifications and triggers actions when notifications are posted."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NotificationManager","kind":"identifier"}],"url":"\/documentation\/easycode\/notificationmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationManager","kind":"identifier"}],"type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/Foundation":{"kind":"symbol","url":"\/documentation\/easycode\/foundation","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Foundation","type":"topic","abstract":[],"role":"collection","title":"Foundation"},"doc://salmik.EasyCode/documentation/EasyCode/DeviceInformation":{"title":"DeviceInformation","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DeviceInformation","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DeviceInformation","kind":"identifier"}],"url":"\/documentation\/easycode\/deviceinformation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceInformation"}],"type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/UserDefaultsStore":{"abstract":[{"type":"text","text":"A class that provides methods to interact with the UserDefaults for saving, loading, updating, and deleting data."}],"navigatorTitle":[{"text":"UserDefaultsStore","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/UserDefaultsStore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserDefaultsStore","kind":"identifier"}],"url":"\/documentation\/easycode\/userdefaultsstore","title":"UserDefaultsStore"},"doc://salmik.EasyCode/documentation/EasyCode/NotificationManagerDelegate":{"role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NotificationManagerDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotificationManagerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationManagerDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines the methods a delegate of "},{"code":"NotificationManager","type":"codeVoice"},{"type":"text","text":" should implement."}],"title":"NotificationManagerDelegate","url":"\/documentation\/easycode\/notificationmanagerdelegate"},"doc://salmik.EasyCode/documentation/EasyCode/NetworkManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkManager","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkManager","url":"\/documentation\/easycode\/networkmanager","type":"topic","role":"symbol","abstract":[{"type":"codeVoice","code":"NetworkManager"},{"type":"text","text":" is a class responsible for managing network requests in your application. It provides"},{"type":"text","text":" "},{"text":"methods for making standard HTTP requests, handling multipart form data, and supports SSL pinning for enhanced security.","type":"text"},{"type":"text","text":" "},{"text":"The class also includes request logging capabilities and offers both callback-based and async\/await APIs.","type":"text"}],"title":"NetworkManager","navigatorTitle":[{"text":"NetworkManager","kind":"identifier"}]},"doc://salmik.EasyCode/documentation/EasyCode/JSONWorker":{"abstract":[{"type":"text","text":"A utility class for working with JSON data."}],"navigatorTitle":[{"kind":"identifier","text":"JSONWorker"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/JSONWorker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONWorker","kind":"identifier"}],"title":"JSONWorker","url":"\/documentation\/easycode\/jsonworker"},"doc://salmik.EasyCode/documentation/EasyCode/PaddedLabel":{"abstract":[{"code":"PaddedLabel","type":"codeVoice"},{"text":" is a custom subclass of ","type":"text"},{"type":"codeVoice","code":"UILabel"},{"type":"text","text":" that adds padding around the label’s text content."}],"navigatorTitle":[{"text":"PaddedLabel","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PaddedLabel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaddedLabel","kind":"identifier"}],"url":"\/documentation\/easycode\/paddedlabel","title":"PaddedLabel"},"doc://salmik.EasyCode/documentation/EasyCode/EasyCodeVersionNumber":{"abstract":[{"text":"Project version number for EasyCode.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EasyCodeVersionNumber","fragments":[{"text":"EasyCodeVersionNumber","kind":"identifier"}],"title":"EasyCodeVersionNumber","url":"\/documentation\/easycode\/easycodeversionnumber"},"doc://salmik.EasyCode/documentation/EasyCode/AVFoundation":{"url":"\/documentation\/easycode\/avfoundation","kind":"symbol","title":"AVFoundation","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/AVFoundation","role":"collection","abstract":[],"type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/ThreadSafe":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThreadSafe"}],"kind":"symbol","abstract":[{"text":"A thread-safe wrapper for any type ","type":"text"},{"code":"T","type":"codeVoice"},{"type":"text","text":", ensuring that read and write operations are performed atomically."}],"role":"symbol","title":"ThreadSafe","url":"\/documentation\/easycode\/threadsafe","type":"topic","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ThreadSafe","navigatorTitle":[{"kind":"identifier","text":"ThreadSafe"}]},"doc://salmik.EasyCode/documentation/EasyCode/HostingView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HostingView","kind":"identifier"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/HostingView","type":"topic","kind":"symbol","abstract":[{"text":"A custom UIView subclass that hosts a SwiftUI view using UIHostingController.","type":"text"}],"role":"symbol","title":"HostingView","url":"\/documentation\/easycode\/hostingview","navigatorTitle":[{"text":"HostingView","kind":"identifier"}]},"doc://salmik.EasyCode/documentation/EasyCode/JailbreakDetection":{"abstract":[{"text":"A class for detecting jailbroken devices using various checks.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JailbreakDetection"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/JailbreakDetection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JailbreakDetection","kind":"identifier"}],"url":"\/documentation\/easycode\/jailbreakdetection","title":"JailbreakDetection"},"doc://salmik.EasyCode/documentation/EasyCode/TipViewController":{"kind":"symbol","url":"\/documentation\/easycode\/tipviewcontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TipViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/TipViewController","abstract":[{"code":"TipViewController","type":"codeVoice"},{"type":"text","text":" is a custom view controller designed to display a tip or informational message to the user."},{"type":"text","text":" "},{"text":"It presents an icon, a title, and a description, along with a close button for dismissing the view.","type":"text"}],"navigatorTitle":[{"text":"TipViewController","kind":"identifier"}],"title":"TipViewController"},"doc://salmik.EasyCode/documentation/EasyCode/MailConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MailConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/easycode\/mailconfiguration","title":"MailConfiguration","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/MailConfiguration","navigatorTitle":[{"kind":"identifier","text":"MailConfiguration"}]},"doc://salmik.EasyCode/documentation/EasyCode/PasswordValidator":{"navigatorTitle":[{"kind":"identifier","text":"PasswordValidator"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PasswordValidator","kind":"identifier"}],"title":"PasswordValidator","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for validating passwords using various strategies."}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PasswordValidator","role":"symbol","url":"\/documentation\/easycode\/passwordvalidator"},"doc://salmik.EasyCode/documentation/EasyCode/DebounceProvider":{"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DebounceProvider","role":"symbol","url":"\/documentation\/easycode\/debounceprovider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DebounceProvider"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DebounceProvider"}],"title":"DebounceProvider","abstract":[{"type":"text","text":"Provides a debounce mechanism for delaying function calls."}]},"doc://salmik.EasyCode/documentation/EasyCode/KeyboardNotificationProtocol":{"type":"topic","abstract":[],"navigatorTitle":[{"text":"KeyboardNotificationProtocol","kind":"identifier"}],"kind":"symbol","title":"KeyboardNotificationProtocol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/KeyboardNotificationProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyboardNotificationProtocol"}],"url":"\/documentation\/easycode\/keyboardnotificationprotocol","role":"symbol"},"doc://salmik.EasyCode/documentation/EasyCode/ContactsWorker":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactsWorker"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContactsWorker","kind":"identifier"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ContactsWorker","kind":"symbol","type":"topic","title":"ContactsWorker","url":"\/documentation\/easycode\/contactsworker","abstract":[{"type":"text","text":"A class responsible for managing contacts in the address book."}]},"doc://salmik.EasyCode/documentation/EasyCode/Parameters":{"url":"\/documentation\/easycode\/parameters","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"Parameters","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Parameters","title":"Parameters","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Parameters"}]},"doc://salmik.EasyCode/documentation/EasyCode/DispatchWorker":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DispatchWorker"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DispatchWorker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DispatchWorker","kind":"identifier"}],"title":"DispatchWorker","url":"\/documentation\/easycode\/dispatchworker"},"doc://salmik.EasyCode/documentation/EasyCode/SelfSizedTableView":{"abstract":[{"type":"text","text":"A "},{"code":"UITableView","type":"codeVoice"},{"text":" subclass that adjusts its height based on its content size, with an optional maximum height.","type":"text"}],"url":"\/documentation\/easycode\/selfsizedtableview","title":"SelfSizedTableView","navigatorTitle":[{"text":"SelfSizedTableView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SelfSizedTableView"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/SelfSizedTableView","type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/ImageCache":{"url":"\/documentation\/easycode\/imagecache","abstract":[{"type":"text","text":"Protocol for caching images, providing subscript access to store and retrieve images by key."}],"navigatorTitle":[{"kind":"identifier","text":"ImageCache"}],"role":"symbol","type":"topic","kind":"symbol","title":"ImageCache","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ImageCache","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageCache"}]},"doc://salmik.EasyCode/documentation/EasyCode/ImageFilter":{"url":"\/documentation\/easycode\/imagefilter","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ImageFilter","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageFilter"}],"type":"topic","navigatorTitle":[{"text":"ImageFilter","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An enumeration representing various image filters and their configurations.","type":"text"}],"title":"ImageFilter"},"doc://salmik.EasyCode/documentation/EasyCode/RegularExpression":{"abstract":[{"text":"A struct that wraps around ","type":"text"},{"type":"codeVoice","code":"NSRegularExpression"},{"type":"text","text":" to provide a more Swift-friendly interface for regular expression operations."}],"navigatorTitle":[{"text":"RegularExpression","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/RegularExpression","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RegularExpression","kind":"identifier"}],"url":"\/documentation\/easycode\/regularexpression","title":"RegularExpression"},"doc://salmik.EasyCode/documentation/EasyCode/FolderTypeProtocol":{"title":"FolderTypeProtocol","url":"\/documentation\/easycode\/foldertypeprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FolderTypeProtocol"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/FolderTypeProtocol","navigatorTitle":[{"kind":"identifier","text":"FolderTypeProtocol"}],"abstract":[{"type":"text","text":"A protocol that defines the required property for a folder type used in the LocalFileManager."}]},"doc://salmik.EasyCode/documentation/EasyCode/EasyCodeVersionString":{"abstract":[{"text":"Project version string for EasyCode.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EasyCodeVersionString","fragments":[{"text":"EasyCodeVersionString","kind":"identifier"}],"title":"EasyCodeVersionString","url":"\/documentation\/easycode\/easycodeversionstring"},"doc://salmik.EasyCode/documentation/EasyCode/LocalFileManager":{"abstract":[{"type":"text","text":"A class that provides methods to interact with the file system for saving, loading, updating, and deleting files."}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/LocalFileManager","title":"LocalFileManager","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalFileManager"}],"navigatorTitle":[{"text":"LocalFileManager","kind":"identifier"}],"url":"\/documentation\/easycode\/localfilemanager"},"doc://salmik.EasyCode/documentation/EasyCode/KeychainKeyProtocol":{"title":"KeychainKeyProtocol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/KeychainKeyProtocol","abstract":[{"type":"text","text":"A protocol that defines the required property for a key used in the Keychain."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeychainKeyProtocol"}],"url":"\/documentation\/easycode\/keychainkeyprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"KeychainKeyProtocol","kind":"identifier"}],"type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/NaturalLanguage":{"type":"topic","kind":"symbol","title":"NaturalLanguage","abstract":[],"url":"\/documentation\/easycode\/naturallanguage","role":"collection","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NaturalLanguage"},"doc://salmik.EasyCode/documentation/EasyCode/NetworkMonitor":{"kind":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkMonitor","url":"\/documentation\/easycode\/networkmonitor","navigatorTitle":[{"kind":"identifier","text":"NetworkMonitor"}],"title":"NetworkMonitor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkMonitor"}],"type":"topic","abstract":[{"text":"Class for monitoring network connection status and type.","type":"text"}],"role":"symbol"},"doc://salmik.EasyCode/documentation/EasyCode/NetworkError":{"url":"\/documentation\/easycode\/networkerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkError","kind":"identifier"}],"navigatorTitle":[{"text":"NetworkError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkError","title":"NetworkError","type":"topic","abstract":[{"type":"codeVoice","code":"NetworkError"},{"type":"text","text":" is an enumeration that defines various errors that can occur during network operations."},{"text":" ","type":"text"},{"type":"text","text":"Each case represents a specific type of error that might be encountered while making network requests or handling their responses."}]},"doc://salmik.EasyCode/documentation/EasyCode/Observable":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"Observable","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Observable","kind":"identifier"}],"title":"Observable","url":"\/documentation\/easycode\/observable","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Observable","abstract":[{"text":"A generic observable class that allows observing changes to its value.","type":"text"}]},"doc://salmik.EasyCode/documentation/EasyCode/MeasureTest":{"abstract":[{"text":"Utility class for measuring execution time of closures.","type":"text"}],"navigatorTitle":[{"text":"MeasureTest","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/MeasureTest","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MeasureTest","kind":"identifier"}],"url":"\/documentation\/easycode\/measuretest","title":"MeasureTest"},"doc://salmik.EasyCode/documentation/EasyCode/EncodingType":{"navigatorTitle":[{"text":"EncodingType","kind":"identifier"}],"title":"EncodingType","type":"topic","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EncodingType","abstract":[{"code":"EncodingType","type":"codeVoice"},{"type":"text","text":" is an enumeration that represents the different types of encoding that can be used"},{"type":"text","text":" "},{"type":"text","text":"when preparing a network request."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodingType"}],"url":"\/documentation\/easycode\/encodingtype"},"doc://salmik.EasyCode/documentation/EasyCode/UserDefaultsStoreKey":{"kind":"symbol","url":"\/documentation\/easycode\/userdefaultsstorekey","title":"UserDefaultsStoreKey","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/UserDefaultsStoreKey","role":"symbol","navigatorTitle":[{"text":"UserDefaultsStoreKey","kind":"identifier"}],"abstract":[{"text":"A protocol that defines the required property for a key used in the UserDefaultsStore.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UserDefaultsStoreKey","kind":"identifier"}],"type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/MultipartFormDataParameter":{"abstract":[],"navigatorTitle":[{"text":"MultipartFormDataParameter","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/MultipartFormDataParameter","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultipartFormDataParameter","kind":"identifier"}],"title":"MultipartFormDataParameter","url":"\/documentation\/easycode\/multipartformdataparameter"},"doc://salmik.EasyCode/documentation/EasyCode/NetworkMonitorDelegate":{"navigatorTitle":[{"text":"NetworkMonitorDelegate","kind":"identifier"}],"url":"\/documentation\/easycode\/networkmonitordelegate","type":"topic","abstract":[{"text":"Delegate protocol for network status changes.","type":"text"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkMonitorDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkMonitorDelegate"}],"title":"NetworkMonitorDelegate","kind":"symbol"},"doc://salmik.EasyCode/documentation/EasyCode/PasswordValidationFactory":{"navigatorTitle":[{"text":"PasswordValidationFactory","kind":"identifier"}],"url":"\/documentation\/easycode\/passwordvalidationfactory","type":"topic","abstract":[{"text":"Factory class for creating password validation strategies based on rules.","type":"text"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PasswordValidationFactory","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PasswordValidationFactory","kind":"identifier"}],"title":"PasswordValidationFactory","kind":"symbol"},"doc://salmik.EasyCode/documentation/EasyCode/UIKit":{"abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/UIKit","type":"topic","url":"\/documentation\/easycode\/uikit","title":"UIKit"},"doc://salmik.EasyCode/documentation/EasyCode/Logger":{"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"url":"\/documentation\/easycode\/logger","type":"topic","abstract":[{"text":"Utility class for logging messages with dividers.","type":"text"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Logger","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"title":"Logger","kind":"symbol"},"doc://salmik.EasyCode/documentation/EasyCode/CoreDataManager":{"abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"CoreDataManager","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easycode\/coredatamanager","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/CoreDataManager","title":"CoreDataManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreDataManager","kind":"identifier"}]},"doc://salmik.EasyCode/documentation/EasyCode/ConsoleLogger":{"title":"ConsoleLogger","abstract":[{"code":"ConsoleLogger","type":"codeVoice"},{"type":"text","text":" is a class responsible for logging network requests and responses to the console."},{"type":"text","text":" "},{"text":"It provides detailed logging, including URLs, HTTP methods, headers, and bodies for both requests and responses.","type":"text"},{"text":" ","type":"text"},{"text":"The logs are formatted for readability and include timestamps, status codes, and any errors encountered.","type":"text"}],"url":"\/documentation\/easycode\/consolelogger","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConsoleLogger"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConsoleLogger","kind":"identifier"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ConsoleLogger","role":"symbol"},"doc://salmik.EasyCode/documentation/EasyCode/EncryptionCryptoProtocol":{"navigatorTitle":[{"text":"EncryptionCryptoProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EncryptionCryptoProtocol"}],"title":"EncryptionCryptoProtocol","type":"topic","url":"\/documentation\/easycode\/encryptioncryptoprotocol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EncryptionCryptoProtocol"},"doc://salmik.EasyCode/documentation/EasyCode/Swift":{"abstract":[],"kind":"symbol","role":"collection","title":"Swift","url":"\/documentation\/easycode\/swift","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/Swift","type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/DynamicHeightCollectionView":{"title":"DynamicHeightCollectionView","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easycode\/dynamicheightcollectionview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DynamicHeightCollectionView","kind":"identifier"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DynamicHeightCollectionView","navigatorTitle":[{"text":"DynamicHeightCollectionView","kind":"identifier"}],"abstract":[{"type":"text","text":"A custom "},{"type":"codeVoice","code":"UICollectionView"},{"type":"text","text":" subclass that adjusts its intrinsic content size based on its content."}]},"doc://salmik.EasyCode/documentation/EasyCode/PerformManager":{"abstract":[{"type":"text","text":"A manager class to handle and perform asynchronous tasks."}],"title":"PerformManager","kind":"symbol","role":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PerformManager","url":"\/documentation\/easycode\/performmanager","navigatorTitle":[{"text":"PerformManager","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PerformManager"}]},"doc://salmik.EasyCode/documentation/EasyCode/HTTPMethod":{"role":"symbol","navigatorTitle":[{"text":"HTTPMethod","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HTTPMethod"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/HTTPMethod","kind":"symbol","title":"HTTPMethod","type":"topic","url":"\/documentation\/easycode\/httpmethod","abstract":[{"type":"codeVoice","code":"HTTPMethod"},{"text":" is an enumeration that represents the various HTTP methods that can be used in a network request.","type":"text"},{"type":"text","text":" "},{"text":"Each case corresponds to a specific HTTP method, with its associated string value.","type":"text"}]},"doc://salmik.EasyCode/documentation/EasyCode/DependencyFactory":{"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"DependencyFactory"},{"type":"text","text":" is responsible for managing the lifecycle of instances in a dependency injection container."},{"type":"text","text":" "},{"type":"text","text":"It supports four types of lifecycles:"}],"kind":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DependencyFactory","type":"topic","url":"\/documentation\/easycode\/dependencyfactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DependencyFactory","kind":"identifier"}],"navigatorTitle":[{"text":"DependencyFactory","kind":"identifier"}],"title":"DependencyFactory","role":"symbol"},"doc://salmik.EasyCode/documentation/EasyCode/ValidationRule":{"kind":"symbol","navigatorTitle":[{"text":"ValidationRule","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationRule","kind":"identifier"}],"abstract":[{"type":"text","text":"An enumeration representing different password validation rules."}],"url":"\/documentation\/easycode\/validationrule","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/ValidationRule","title":"ValidationRule","type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/UnmanagedWrapper":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A class that wraps an unmanaged reference to an object of type "},{"code":"T","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/easycode\/unmanagedwrapper","navigatorTitle":[{"text":"UnmanagedWrapper","kind":"identifier"}],"title":"UnmanagedWrapper","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/UnmanagedWrapper","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UnmanagedWrapper","kind":"identifier"}]},"doc://salmik.EasyCode/documentation/EasyCode/PasswordValidationStrategy":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PasswordValidationStrategy"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PasswordValidationStrategy"}],"abstract":[{"type":"text","text":"Protocol defining a strategy for validating passwords."}],"title":"PasswordValidationStrategy","type":"topic","url":"\/documentation\/easycode\/passwordvalidationstrategy","kind":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/PasswordValidationStrategy"},"doc://salmik.EasyCode/documentation/EasyCode":{"type":"topic","role":"collection","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode","kind":"symbol","url":"\/documentation\/easycode","title":"EasyCode","abstract":[]},"doc://salmik.EasyCode/documentation/EasyCode/DataBaseNameProtocol":{"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/DataBaseNameProtocol","title":"DataBaseNameProtocol","navigatorTitle":[{"kind":"identifier","text":"DataBaseNameProtocol"}],"url":"\/documentation\/easycode\/databasenameprotocol","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DataBaseNameProtocol","kind":"identifier"}],"type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/HTTPHeaders":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/HTTPHeaders","navigatorTitle":[{"kind":"identifier","text":"HTTPHeaders"}],"title":"HTTPHeaders","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"HTTPHeaders","kind":"identifier"}],"url":"\/documentation\/easycode\/httpheaders","role":"symbol"},"doc://salmik.EasyCode/documentation/EasyCode/EndPointProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EndPointProtocol"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"EndPointProtocol"},{"text":" is a protocol that defines the essential properties and methods required to create","type":"text"},{"type":"text","text":" "},{"text":"a network endpoint. It provides a blueprint for configuring the various aspects of a network request,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as the URL, HTTP method, headers, parameters, and encoding."}],"role":"symbol","title":"EndPointProtocol","url":"\/documentation\/easycode\/endpointprotocol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EndPointProtocol","type":"topic","navigatorTitle":[{"text":"EndPointProtocol","kind":"identifier"}]},"doc://salmik.EasyCode/documentation/EasyCode/NetworkResponseProtocol":{"url":"\/documentation\/easycode\/networkresponseprotocol","abstract":[{"type":"codeVoice","code":"NetworkResponseProtocol"},{"text":" is a protocol that defines the structure of a network response.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It includes properties for checking the success of the response, the status code, the data received,"},{"type":"text","text":" "},{"text":"any errors encountered, and the headers associated with the response.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/NetworkResponseProtocol","navigatorTitle":[{"text":"NetworkResponseProtocol","kind":"identifier"}],"title":"NetworkResponseProtocol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NetworkResponseProtocol","kind":"identifier"}]},"doc://salmik.EasyCode/documentation/EasyCode/KeychainService":{"title":"KeychainService","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/KeychainService","abstract":[{"text":"A class that provides methods to interact with the Keychain for saving, loading, updating, and deleting data.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KeychainService"}],"url":"\/documentation\/easycode\/keychainservice","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeychainService"}],"type":"topic"},"doc://salmik.EasyCode/documentation/EasyCode/BiometricIDAuth":{"type":"topic","abstract":[{"type":"text","text":"Class handling biometric authentication using LocalAuthentication framework."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BiometricIDAuth","kind":"identifier"}],"title":"BiometricIDAuth","navigatorTitle":[{"kind":"identifier","text":"BiometricIDAuth"}],"url":"\/documentation\/easycode\/biometricidauth","role":"symbol","kind":"symbol","identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/BiometricIDAuth"},"doc://salmik.EasyCode/documentation/EasyCode/TemporaryImageCache":{"abstract":[{"type":"text","text":"Implementation of "},{"type":"codeVoice","code":"ImageCache"},{"type":"text","text":" using "},{"code":"NSCache","type":"codeVoice"},{"type":"text","text":" to temporarily store images in memory."}],"title":"TemporaryImageCache","type":"topic","url":"\/documentation\/easycode\/temporaryimagecache","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemporaryImageCache","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TemporaryImageCache"}],"identifier":"doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/TemporaryImageCache"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EasyCodeVersionNumber","doc:\/\/salmik.EasyCode\/documentation\/EasyCode\/EasyCodeVersionString"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}